import type { CurriculumModule } from '../types/curriculum';

export const MASTER_MODULES: CurriculumModule[] = [
  // PART 1: SILICON SEMICONDUCTORS & PHYSICAL PHYSICS
  {
    id: 'm1',
    moduleNumber: 1,
    title: '1. Atomic Physics & Charge Carriers',
    subtitle: 'Electrons, Silicon Crystal Lattice, Doping (P-Type & N-Type)',
    description: 'How pure silicon crystal lattices are doped with phosphorus and boron to create free electrons and positive holes for electrical conduction.',
    iconName: 'Atom',
    lessons: [],
    capstoneProject: { id: 'p1', title: 'Simulate Doped Silicon Conduction', description: 'Silicon physics capstone', objective: 'Test electron-hole mobility' },
  },
  {
    id: 'm2',
    moduleNumber: 2,
    title: '2. MOSFET Transistors & CMOS Switching',
    subtitle: 'Gate Oxide, Source/Drain, NMOS vs PMOS, Threshold Voltage (Vth)',
    description: 'The physical mechanics of metal-oxide-semiconductor field-effect transistors and complementary pairing for zero static power loss.',
    iconName: 'Zap',
    lessons: [],
    capstoneProject: { id: 'p2', title: 'Build a CMOS Inverter Pair', description: 'CMOS capstone', objective: 'Verify zero static power loss' },
  },
  {
    id: 'm3',
    moduleNumber: 3,
    title: '3. Voltage Margins & Digital Abstraction',
    subtitle: 'Analog Voltage (0V-5V), Noise Margins (0.8V-2V), Binary 0 and 1',
    description: 'Mapping noisy continuous analog voltages into precise digital binary logic states using forbidden voltage noise margin buffer zones.',
    iconName: 'Sliders',
    lessons: [],
    capstoneProject: { id: 'p3', title: 'Build a Voltage Noise Buffer', description: 'Voltage capstone', objective: 'Filter signal noise' },
  },

  // PART 2: BINARY MATH, ENCODINGS & BOOLEAN ALGEBRA
  {
    id: 'm4',
    moduleNumber: 4,
    title: '4. Binary Positional Notation & Two’s Complement',
    subtitle: 'Base-2, Base-16 Hexadecimal, Nibbles, Bytes, Signed Negative Numbers',
    description: 'Representing numbers in binary base-2 positional notation, hexadecimal mapping, and encoding negative integers with two’s complement.',
    iconName: 'Binary',
    lessons: [],
    capstoneProject: { id: 'p4', title: 'Build a 2’s Complement Calculator', description: 'Binary capstone', objective: 'Invert and add 1 for negatives' },
  },
  {
    id: 'm5',
    moduleNumber: 5,
    title: '5. Floating-Point Numbers & Character Encodings',
    subtitle: 'IEEE 754 Floating Point (Sign, Exponent, Mantissa), ASCII, UTF-8',
    description: 'Encoding fractional decimals into binary IEEE 754 format and mapping text characters across ASCII, UTF-8, and UTF-16 Unicode Standards.',
    iconName: 'FileText',
    lessons: [],
    capstoneProject: { id: 'p5', title: 'Build an IEEE 754 Binary Converter', description: 'Encoding capstone', objective: 'Parse float bits' },
  },
  {
    id: 'm6',
    moduleNumber: 6,
    title: '6. Boolean Algebra & Logic Optimization',
    subtitle: 'Truth Tables, Boolean Laws, De Morgan’s Theorems, Karnaugh Maps (K-Maps)',
    description: 'Algebraic manipulation of Boolean expressions, gate reduction techniques, and K-Map logic simplification in microchips.',
    iconName: 'CheckSquare',
    lessons: [],
    capstoneProject: { id: 'p6', title: 'Optimize a K-Map Logic Circuit', description: 'Boolean capstone', objective: 'Reduce gate count' },
  },

  // PART 3: COMBINATIONAL & SEQUENTIAL CIRCUITS
  {
    id: 'm7',
    moduleNumber: 7,
    title: '7. Digital Logic Gates in Silicon',
    subtitle: '7 Logic Gates (NOT, NAND, AND, NOR, OR, XOR, XNOR), Transistor Counts',
    description: 'Building all 7 fundamental logic gates using PMOS and NMOS complementary pull-up/pull-down transistor schematics.',
    iconName: 'Layers',
    lessons: [],
    capstoneProject: { id: 'p7', title: 'Build Universal NAND Gate Network', description: 'Logic gate capstone', objective: 'Build XOR from NANDs' },
  },
  {
    id: 'm8',
    moduleNumber: 8,
    title: '8. Binary Adders & Carry Lookahead',
    subtitle: 'Half Adder, Full Adder, Ripple Carry Delay, Carry Lookahead Adders (CLA)',
    description: 'Combining XOR and AND gates into Full Adders, analyzing propagation delays, and optimizing addition with Carry Lookahead logic.',
    iconName: 'PlusCircle',
    lessons: [],
    capstoneProject: { id: 'p8', title: 'Build a 4-Bit Carry Lookahead Adder', description: 'Adder capstone', objective: 'Eliminate ripple delay' },
  },
  {
    id: 'm9',
    moduleNumber: 9,
    title: '9. Multiplexers, Demultiplexers & Decoders',
    subtitle: 'MUX 2:1, 4:1, 8:1, DEMUX, 3-to-8 Decoders, Tri-State Bus Buffers',
    description: 'Hardware routing switches that select 1 out of N data channels using binary control signals and tri-state bus drivers.',
    iconName: 'GitBranch',
    lessons: [],
    capstoneProject: { id: 'p9', title: 'Build an 8-to-1 Multiplexer', description: 'MUX capstone', objective: 'Route data lines' },
  },

  // PART 4: MICROPROCESSOR ARCHITECTURE & CPU CORE
  {
    id: 'm10',
    moduleNumber: 10,
    title: '10. Latches, Edge-Triggered Flip-Flops & Registers',
    subtitle: 'SR Latches, D Flip-Flops, Setup/Hold Times, 8-Bit Parallel Registers',
    description: 'Feedback loops in digital logic creating bistable memory cells that store data on clock signal rising edges.',
    iconName: 'Database',
    lessons: [],
    capstoneProject: { id: 'p10', title: 'Build an 8-Bit D Register File', description: 'Sequential capstone', objective: 'Store data on CLK edge' },
  },
  {
    id: 'm11',
    moduleNumber: 11,
    title: '11. The Arithmetic Logic Unit (ALU) & Status Flags',
    subtitle: 'Parallel ALU, Bitwise Operations, Status Flags (Zero Z, Overflow V, Negative N, Carry C)',
    description: 'The core computational engine of the processor, handling 32-bit math, bit shifts, and updating status flag registers for branching.',
    iconName: 'Cpu',
    lessons: [],
    capstoneProject: { id: 'p11', title: 'Build a 32-Bit ALU with Flags', description: 'ALU capstone', objective: 'Compute and set Z/V/N flags' },
  },
  {
    id: 'm12',
    moduleNumber: 12,
    title: '12. von Neumann & Harvard CPU Architecture',
    subtitle: 'Program Counter (PC), Instruction Register (IR), MAR, MDR, Control Unit (CU)',
    description: 'The structural layout of microprocessors, memory buses, instruction registers, and microcode control unit execution.',
    iconName: 'Server',
    lessons: [],
    capstoneProject: { id: 'p12', title: 'Build a von Neumann Control Unit', description: 'Architecture capstone', objective: 'Fetch and decode opcodes' },
  },
  {
    id: 'm13',
    moduleNumber: 13,
    title: '13. 5-Stage Instruction Pipelining & Branch Prediction',
    subtitle: 'Fetch, Decode, Execute, Memory, Writeback; Pipeline Hazards & Speculative Execution',
    description: 'Overlapping instruction execution stages in modern CPUs to achieve 1 Instruction Per Cycle (IPC), hazards, and branch predictors.',
    iconName: 'Activity',
    lessons: [],
    capstoneProject: { id: 'p13', title: 'Simulate a 5-Stage RISC Pipeline', description: 'Pipeline capstone', objective: 'Resolve data hazards' },
  },

  // PART 5: MEMORY HIERARCHY, CACHE & STORAGE
  {
    id: 'm14',
    moduleNumber: 14,
    title: '14. Cache Memory Architecture & Coherence',
    subtitle: 'SRAM 6T Cells, L1/L2/L3 Caches, Set-Associativity, Cache Misses, MESI Protocol',
    description: 'High-speed 6-transistor SRAM cache cells, cache line eviction algorithms, set associativity, and multi-core MESI cache coherence.',
    iconName: 'HardDrive',
    lessons: [],
    capstoneProject: { id: 'p14', title: 'Build an L1 Set-Associative Cache Simulator', description: 'Cache capstone', objective: 'Track Cache Hits/Misses' },
  },
  {
    id: 'm15',
    moduleNumber: 15,
    title: '15. Main RAM (DRAM) & SSD Storage Cells',
    subtitle: '1T-1C DRAM Capacitors, Refresh Cycles, DDR5 Bus, Flash NVMe NAND Blocks',
    description: 'Dynamic RAM capacitor storage cells, row/column address strobes (RAS/CAS), and non-volatile NAND Flash SSD floating-gate transistors.',
    iconName: 'Grid',
    lessons: [],
    capstoneProject: { id: 'p15', title: 'Build a DRAM Refresh Cycle Engine', description: 'DRAM capstone', objective: 'Maintain capacitor charges' },
  },

  // PART 6: MACHINE CODE, ASSEMBLY & COMPILERS
  {
    id: 'm16',
    moduleNumber: 16,
    title: '16. Instruction Set Architecture (ISA)',
    subtitle: 'RISC-V vs x86-64, Opcode Encodings, R-Type, I-Type, J-Type Instructions',
    description: 'The binary contract between software and hardware, defining instruction bit fields, register specs, and memory addressing modes.',
    iconName: 'Terminal',
    lessons: [],
    capstoneProject: { id: 'p16', title: 'Build a RISC-V Instruction Encoder', description: 'ISA capstone', objective: 'Encode assembly into binary' },
  },
  {
    id: 'm17',
    moduleNumber: 17,
    title: '17. Assemblers, Linkers & Executable Formats',
    subtitle: 'Two-Pass Assembly, Symbol Tables, Object Files (.o), ELF/PE Header, Relocation',
    description: 'Translating human-readable assembly mnemonics into machine code binary, symbol resolution, and executable file headers.',
    iconName: 'FileCode',
    lessons: [],
    capstoneProject: { id: 'p17', title: 'Build a Two-Pass Assembler', description: 'Assembler capstone', objective: 'Resolve label addresses' },
  },
  {
    id: 'm18',
    moduleNumber: 18,
    title: '18. Compiler Pipelines & LLVM Code Optimization',
    subtitle: 'Lexer Tokenization, AST Parser, Intermediate Representation (IR), Native CodeGen',
    description: 'How high-level C/C++/Rust code is tokenized, parsed into Abstract Syntax Trees, optimized via LLVM passes, and compiled to native code.',
    iconName: 'Code',
    lessons: [],
    capstoneProject: { id: 'p18', title: 'Build a Compiler Lexer & AST Parser', description: 'Compiler capstone', objective: 'Parse code into AST tree' },
  },

  // PART 7: OPERATING SYSTEMS, VIRTUAL MEMORY & RUNTIMES
  {
    id: 'm19',
    moduleNumber: 19,
    title: '19. Operating System Kernels & System Calls',
    subtitle: 'Monolithic Kernels, Syscalls (read/write/fork), Interrupt Vectors (IRQ), Context Switching',
    description: 'Privileged execution modes (Ring 0 vs Ring 3), system call traps, hardware interrupt handlers, and process context switching.',
    iconName: 'Shield',
    lessons: [],
    capstoneProject: { id: 'p19', title: 'Build an OS Syscall Trap Handler', description: 'OS capstone', objective: 'Handle Ring 0 trap calls' },
  },
  {
    id: 'm20',
    moduleNumber: 20,
    title: '20. Virtual Memory, Paging & MMU Hardware',
    subtitle: 'Memory Management Unit (MMU), Page Tables, TLB Cache, Page Faults',
    description: 'Hardware virtual memory translation, converting process virtual addresses to physical RAM using multi-level page tables and TLB caches.',
    iconName: 'Sliders',
    lessons: [],
    capstoneProject: { id: 'p20', title: 'Build an MMU Page Table Translator', description: 'Virtual Memory capstone', objective: 'Translate Virtual to Physical RAM' },
  },
  {
    id: 'm21',
    moduleNumber: 21,
    title: '21. JavaScript Engine & Memory Runtimes',
    subtitle: 'V8 Engine, Call Stack Frames, Memory Heap Allocation, Mark-and-Sweep GC, Event Loop',
    description: 'Executing dynamic languages inside runtimes, stack allocation, heap garbage collection algorithms, and asynchronous event loops.',
    iconName: 'PlayCircle',
    lessons: [],
    capstoneProject: { id: 'p21', title: 'Build a V8 Call Stack & Event Loop', description: 'Runtime capstone', objective: 'Execute Macrotasks & Microtasks' },
  },

  // PART 8: COMPUTER NETWORKING, BROWSERS & WEB
  {
    id: 'm22',
    moduleNumber: 22,
    title: '22. Web Browser Rendering Engine Pipeline',
    subtitle: 'HTML Tokenizer, DOM, CSSOM, Render Tree, Layout Reflow, Paint, GPU Compositing',
    description: 'How web browser engines parse HTML/CSS streams, build layout trees, compute exact pixel coordinates, and paint via GPU shaders.',
    iconName: 'Globe',
    lessons: [],
    capstoneProject: { id: 'p22', title: 'Build a DOM Render Tree & Painter', description: 'Browser capstone', objective: 'Layout HTML elements' },
  },
  {
    id: 'm23',
    moduleNumber: 23,
    title: '23. Computer Networking & Web Stack',
    subtitle: 'OSI 7 Layers, TCP/IP Sockets, DNS Lookup, TLS Handshake, HTTP/3 QUIC Protocol',
    description: 'End-to-end packet traversal across the global Internet, socket connections, TCP congestion control, TLS encryption, and HTTP/3.',
    iconName: 'Network',
    lessons: [],
    capstoneProject: { id: 'p23', title: 'Build a TCP 3-Way Handshake Engine', description: 'Networking capstone', objective: 'Establish socket connection' },
  },

  // PART 9: ARTIFICIAL INTELLIGENCE, DEEP LEARNING & LLMs
  {
    id: 'm24',
    moduleNumber: 24,
    title: '24. Neural Networks, Transformers & LLM Inference',
    subtitle: 'Perceptrons, Backprop & Gradient Descent, Multi-Head Self-Attention (Q,K,V), Tokenizer, LLM Inference',
    description: 'The mathematics and hardware of Artificial Intelligence: matrix multiplication on GPUs, self-attention matrices, byte-pair tokenization, and LLM text generation.',
    iconName: 'Bot',
    lessons: [],
    capstoneProject: { id: 'p24', title: 'Build Mini ChatGPT / Transformer Engine', description: 'AI capstone', objective: 'Compute Attention & Sample Tokens' },
  },
];
